### ISSUE TITLE
About the Experiments

### ISSUE THREAD

**Issue by haohaodw** [Lackel/AGLA#3]
A very nice work！ I would like to ask what the temperature setting of the experiment is, are all methods tested at the same temperature?

**Comment by Lackel** [comment]
Hi, thanks for your interest. The temperature is set to 1 for all experiments.

**Comment by haohaodw** [comment]
Thank you for your reply. I have another question. There are many versions of llava. Which version are you using? Can you share the Huggingface link?

**Comment by Lackel** [comment]
Hi, the llava used in our model is included in https://github.com/Lackel/AGLA/tree/main/llava. The file is cited from VCD (https://github.com/DAMO-NLP-SG/VCD), so we do not know the specific version since the source code of llava is frequently updated.

**Comment by haohaodw** [comment]
Thank you for your reply. Maybe my expression is not clear. I am not referring to the source code of llava, but the checkpoint of llava. I want to know which llava model is used in the paper. Can you share the corresponding Huggingface link？

**Comment by Lackel** [comment]
Hi, this is the llava version we used https://huggingface.co/liuhaotian/llava-v1.5-7b.

**Comment by wzczc** [comment]
> Thank you for your reply. Maybe my expression is not clear. I am not referring to the source code of llava, but the checkpoint of llava. I want to know which llava model is used in the paper. Can you share the corresponding Huggingface link？

@haohaodw Hi, have you reproduced the results? @Lackel  I used the official LLaVA POPE evaluation code, and the results I got differ significantly from those in the paper, but they are consistent with the results in the LLaVA paper.
